[package]
name = "mental-knowledge-base"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mental-domain.workspace = true
mental-llm-connector.workspace = true
sqlx.workspace = true
async-trait.workspace = true
uuid.workspace = true
anyhow.workspace = true
tracing.workspace = true
